-- Built In Functions_2/16
local Hotdog = "PlayerPart"
local MelonFriend = "PlayerPart2"
local Melon = game.Workspace.LessonModels:FindFirstChild(MelonFriend)
print(Melon)
local Realdog = game.Workspace.LessonModels:FindFirstChild(Hotdog)
print(Realdog)
melon = game.Workspace.LessonModels:WaitForChild(MelonFriend)
print(melon)
hotdog = game.Workspace.LessonModels:WaitForChild(Hotdog)
print(hotdog)